# Generated by Django 3.1.2 on 2020-10-14 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrap', '0002_auto_20201012_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrap',
            name='users_list',
            field=models.ManyToManyField(related_name='users_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
