# Generated by Django 3.1.2 on 2020-10-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_scrap_users_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrap',
            name='users_list',
        ),
    ]
