# Generated by Django 3.1.2 on 2020-10-14 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_auto_20201012_2024'),
        ('users', '0003_auto_20201014_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='scrap.scrap'),
        ),
    ]
