# Generated by Django 3.1.2 on 2020-10-14 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_auto_20201012_2024'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20201014_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_list', to='scrap.scrap'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
