# Generated by Django 3.1.2 on 2020-10-14 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_scrap_users_list'),
        ('users', '0008_profile_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='topics',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='scrap.scrap'),
        ),
    ]
