# Generated by Django 3.1.2 on 2020-10-14 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_scrap_users_list'),
        ('users', '0011_auto_20201014_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='topics',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scrap.scrap'),
        ),
    ]
