# Generated by Django 3.1.2 on 2020-10-14 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201014_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='topics',
            new_name='subs',
        ),
    ]
