# Generated by Django 3.1.2 on 2020-10-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_scrap_users_list'),
        ('users', '0013_auto_20201014_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subs',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='scrap.scrap'),
        ),
    ]
