# Generated by Django 3.1.2 on 2020-10-14 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201014_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subs',
        ),
    ]
