# Generated by Django 3.1.2 on 2020-10-14 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_scrap_users_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0015_remove_profile_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='scrap.scrap'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
